# Generated by Django 6.0.3 on 2026-04-18 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_715af4_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('scenario_assigned', 'Scenario Assigned'), ('session_completed', 'Session Completed'), ('session_deadline_approaching', 'Deadline Approaching'), ('container_unavailable', 'Container Unavailable')], max_length=40),
        ),
    ]
