# Generated by Django 6.0.3 on 2026-04-05 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage_order', models.PositiveSmallIntegerField(default=1)),
                ('version_snapshot', models.PositiveIntegerField(help_text='Scenario version captured when this session started (BR-12).')),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], db_index=True, default='provisioning', max_length=15)),
                ('ethical_warning_acknowledged', models.BooleanField(default=False, help_text="True once the user has clicked 'I Understand' on the ethical warning screen. Session cannot advance until True. (BR-04)")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation Session',
                'verbose_name_plural': 'Simulation Sessions',
                'db_table': 'simulation_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional deadline for completing this assignment (FR-22).', null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
