# Generated by Django 6.0.3 on 2026-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationsession',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], db_index=True, default='provisioning', max_length=15),
        ),
    ]
