# Generated by Django 6.0.3 on 2026-04-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total number of times users have reached this stage.')),
                ('total_detections', models.PositiveIntegerField(default=0, help_text='Total number of successful detections at this stage.')),
                ('cumulative_time_to_detect_ms', models.BigIntegerField(default=0, help_text='Running sum of time_to_detect values from UserAction. Divide by total_detections to get average (FR-15, FR-16).')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stage', models.OneToOneField(help_text='One metric record per stage (BR-09).', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metric', to='scenarios.stage')),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'db_table': 'analytics_metric',
            },
        ),
    ]
