# Generated by Django 6.0.3 on 2026-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreEducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(db_index=True, help_text="MITRE ATT&CK technique ID, e.g. 'T1566' or 'T1204.002'.", max_length=20, unique=True)),
                ('title', models.CharField(help_text="Human-readable technique name, e.g. 'Spearphishing Link'.", max_length=255)),
                ('url', models.URLField(help_text='Canonical MITRE ATT&CK page or external resource URL.')),
                ('description', models.TextField(blank=True, help_text='Brief plain-English summary shown alongside the link.')),
            ],
            options={
                'verbose_name': 'MITRE Educational Resource',
                'verbose_name_plural': 'MITRE Educational Resources',
                'db_table': 'mitre_educational_resource',
                'ordering': ['mitre_id'],
            },
        ),
    ]
