# Generated by Django 6.0.3 on 2026-04-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0002_initial'),
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_time', models.CharField(help_text='Role the participant held when this action was recorded. Stored as a plain string — not a FK — to satisfy BR-05 anonymization requirements.', max_length=20)),
                ('action_type', models.CharField(choices=[('click', 'Click'), ('download', 'Download'), ('flag', 'Flag as Suspicious'), ('submit', 'Form Submit'), ('view', 'View')], max_length=15)),
                ('detection_quality', models.FloatField(blank=True, help_text='Scored 0.0–1.0 by StageEngine after evaluating the action against detection_criteria JSON (telemetry_detection_sequence).', null=True)),
                ('time_to_detect', models.IntegerField(blank=True, help_text='Milliseconds from attack presentation to user detection action.', null=True)),
                ('detected', models.BooleanField(blank=True, help_text='True = attack detected, False = missed, None = not yet evaluated.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='simulations.simulationsession')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='scenarios.stage')),
            ],
            options={
                'verbose_name': 'User Action',
                'verbose_name_plural': 'User Actions',
                'db_table': 'user_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="e.g. 'click', 'input', 'scroll', 'navigation'", max_length=50)),
                ('offset_ms', models.IntegerField(help_text='Time offset in milliseconds from the moment the attack vector was rendered to the user. Used for time_to_detect calculation (FR-15).')),
                ('element', models.CharField(help_text='CSS selector or semantic ID of the interacted element.', max_length=255)),
                ('action', models.ForeignKey(db_column='action_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='telemetry.useraction')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'db_table': 'event_log',
                'ordering': ['action', 'offset_ms'],
            },
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['session', 'stage'], name='user_action_session_1de9be_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['stage', 'detected'], name='user_action_stage_i_5c4a62_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['action', 'offset_ms'], name='event_log_action__416fae_idx'),
        ),
    ]
