# Generated by Django 6.0.3 on 2026-04-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['action', 'offset_ms']},
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='element',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='offset_ms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('click', 'Click'), ('download', 'Download'), ('flag', 'Flag as Suspicious'), ('submit', 'Form Submit'), ('view', 'View'), ('hover', 'Hover'), ('delete', 'Delete'), ('reply', 'Reply')], max_length=15),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='detection_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='role_at_time',
            field=models.CharField(help_text='Role snapshot at time of action. Not a FK (BR-05).', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='time_to_detect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', 'element'], name='event_log_event_t_4a07e1_idx'),
        ),
    ]
