# Generated by Django 6.0.3 on 2026-04-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_container_id', models.CharField(blank=True, help_text='ID returned by docker-py after container creation.', max_length=64)),
                ('base_url', models.CharField(blank=True, help_text='Internal container URL (e.g. http://container-host:PORT). Populated by the async provisioning task once the container is active (ScenarioLifecycle_sequence).', max_length=255)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('stopped', 'Stopped'), ('error', 'Error')], db_index=True, default='provisioning', max_length=15)),
                ('host_port', models.PositiveIntegerField(blank=True, help_text="Host port mapped to the container's internal service port.", null=True)),
                ('provisioned_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text="Timestamp when the container transitioned to 'active'.", null=True)),
                ('session', models.OneToOneField(db_column='session_id', help_text='One container per simulation session.', on_delete=django.db.models.deletion.CASCADE, related_name='container', to='simulations.simulationsession')),
            ],
            options={
                'verbose_name': 'Scenario Container',
                'verbose_name_plural': 'Scenario Containers',
                'db_table': 'scenario_container',
            },
        ),
    ]
