# Generated by Django 6.0.3 on 2026-04-05 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-incremented on every update (BR-12).')),
                ('container_image', models.CharField(help_text='Docker image tag pulled by the DockerOrchestrator.', max_length=255)),
                ('active_status', models.BooleanField(db_index=True, default=False, help_text='Only active scenarios appear in assignment lists (BR-06).')),
                ('difficulty', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'scenario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.PositiveSmallIntegerField(help_text='Position in the execution sequence. Unique per scenario (BR-08).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('interview', 'Interview'), ('technical_assessment', 'Technical Assessment'), ('onboarding', 'Onboarding')], help_text='Recruitment phase this stage represents (DR-2).', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
                'db_table': 'stage',
                'ordering': ['scenario', 'stage_order'],
            },
        ),
        migrations.CreateModel(
            name='AttackVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_type', models.CharField(choices=[('phishing_link', 'Phishing Link'), ('malicious_file', 'Malicious File Download'), ('credential_form', 'Credential Harvesting Form'), ('fake_identity', 'Fake Identity Indicator'), ('geographic', 'Geographic Inconsistency'), ('urgency', 'Urgency Manipulation')], max_length=30)),
                ('mitre_id', models.CharField(blank=True, help_text='MITRE ATT&CK technique ID, e.g. T1566 (DR-1, BR-03).', max_length=20)),
                ('container_path', models.CharField(help_text='Path inside the simulation container that renders this vector.', max_length=255)),
                ('detection_criteria', models.JSONField(default=dict, help_text='JSON schema evaluated by StageEngine against telemetry events to determine detection success (telemetry_detection_sequence).')),
                ('difficulty', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('dataset_features', models.ManyToManyField(blank=True, help_text='Dataset-derived fraud indicators used to make this vector realistic (DR-3). Cannot delete a DatasetFeature that is referenced here while the parent scenario is active (BR-11).', related_name='attack_vectors', to='datasets.datasetfeature')),
            ],
            options={
                'verbose_name': 'Attack Vector',
                'verbose_name_plural': 'Attack Vectors',
                'db_table': 'attack_vector',
                'ordering': ['stage', 'vector_type'],
            },
        ),
    ]
