# Generated by Django 6.0.3 on 2026-04-05 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_scenarios', through='simulations.Assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='scenarios.scenario'),
        ),
        migrations.AddField(
            model_name='attackvector',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_vectors', to='scenarios.stage'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('scenario', 'stage_order')},
        ),
    ]
