# Generated by Django 6.0.3 on 2026-04-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='company_profile',
            field=models.TextField(blank=True, help_text='Fictional company details used to brand all stages consistently. Simulation containers read this to render a coherent fake company. Example: Name: Acme Corp\\nIndustry: Finance\\nLocation: New York, NY'),
        ),
    ]
