# Generated by Django 6.0.3 on 2026-04-11 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('scenarios', '0003_scenario_company_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attackvector',
            options={'ordering': ['stage', 'vector_type']},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['scenario', 'stage_order']},
        ),
        migrations.AlterField(
            model_name='attackvector',
            name='container_path',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AlterField(
            model_name='attackvector',
            name='dataset_features',
            field=models.ManyToManyField(blank=True, related_name='attack_vectors', to='datasets.datasetfeature'),
        ),
        migrations.AlterField(
            model_name='attackvector',
            name='detection_criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='attackvector',
            name='mitre_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='active_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='company_profile',
            field=models.TextField(blank=True, help_text='Fictional company used to brand all stages consistently. Example: Name: Acme Corp\nIndustry: Finance\nLocation: New York, NY'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='container_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('interview', 'Interview'), ('technical_assessment', 'Technical Assessment'), ('onboarding', 'Onboarding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_order',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
