# Generated by Django 6.0.3 on 2026-04-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_alter_attackvector_options_alter_scenario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, individual (self-registered) users can start this scenario without needing an Assignment. Has no effect for organizational users.'),
        ),
    ]
