# Generated by Django 6.0.3 on 2026-04-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('organizational', 'Organizational'), ('individual', 'Individual')], default='organizational', help_text='Organizational: admin-created, gets assigned scenarios. Individual: self-registered, sees public scenarios.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('hr_personnel', 'HR Personnel'), ('job_seeker', 'Job Seeker'), ('both', 'Both (HR + Job Seeker)')], default='job_seeker', max_length=20),
        ),
    ]
